services:
  - type: web
    name: alitonk
    runtime: static
    buildCommand: npm run build
    staticPublishPath: ./public
    pullRequestPreviewsEnabled: false
    autoDeploy: true
    headers:
      - path: /*
        name: Cache-Control
        value: public, max-age=0, must-revalidate
      - path: /js/*
        name: Cache-Control
        value: public, max-age=31536000, immutable
      - path: /data/*
        name: Cache-Control
        value: public, max-age=300, must-revalidate
    routes:
      - type: rewrite
        source: /contact
        destination: /contact.html
      - type: rewrite
        source: /about
        destination: /about.html
      - type: rewrite
        source: /donate
        destination: /donate.html
      - type: rewrite
        source: /token
        destination: /token.html
      - type: rewrite
        source: /faq
        destination: /faq.html
